# Generated by Django 3.0.5 on 2020-06-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='content',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
